
#pragma once

/* FIXME error code */
#define OK 0
#define CMSISDAP_ERR_FATAL						1
#define CMSISDAP_ERR_INVALID_ARGUMENT			2
#define CMSISDAP_ERR_NO_MEMORY					3
#define CMSISDAP_ERR_DAP_RES					4
#define CMSISDAP_ERR_ACKFAULT					5
#define CMSISDAP_ERR_INVALID_TX_LEN				6
#define CMSISDAP_ERR_USBHID_INIT				7
#define CMSISDAP_ERR_USBHID_OPEN				8
#define CMSISDAP_ERR_USBHID_NOT_FOUND_DEVICE	9
#define CMSISDAP_ERR_USBHID_WRITE				10
#define CMSISDAP_ERR_USBHID_TIMEOUT				11
#define CMSISDAP_ERR_USBHID_EXIT				12
#define CMSISDAP_ERR_INVALID_STATUS				13
